server:
  port: ${port:9091}
#  port: 9091
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springclound
    username: root
    password: 123456
  application:
    name: user-service
mybatis:
  type-aliases-package: com.jiacool.user.pojo
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    # 设置ip 地址
    ip-address: 127.0.0.1
    # 更倾向于 使用ip地址
    prefer-ip-address: true
    # 服务续约(renew)的间隔，默认为30秒
    lease-renewal-interval-in-seconds: 10
    # 服务失效时间，默认值90秒
    lease-expiration-duration-in-seconds: 30
test:
    name: sky is red
